### ISSUE TITLE
Can't make Fritz!Presence plugin working

### ISSUE THREAD

**Issue by santricity** [belzetrigger/domoticz-FritzPresence#1]
Hi, I'm running the latest stable Domoticz 2020.1 on Raspbian Buster (up to date) and latest Fritz!Presence plugin. But I can't make the plugin running:

2020-04-06 10:25:22.788 Error: (FritzPresence) failed to load 'plugin.py', Python Path used was '/home/pi/domoticz/plugins/domoticz-FritzPresence/:/usr/lib/python37.zip:/usr/lib/python3.7:/usr/lib/python3.7/lib-dynload:/usr/local/lib/python3.7/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.7/dist-packages'.
2020-04-06 10:25:22.789 Error: (Fritz!Presence) Module Import failed, exception: 'NameError'
2020-04-06 10:25:22.789 Error: (Fritz!Presence) Error Line details not available.

and from time to time:
2020-04-06 10:29:39.524 Error: Fritz!Presence hardware (7) thread seems to have ended unexpectedly

My sys.path.append section in plugin.py:
sys.path
sys.path.append('/usr/lib/python3/dist-packages')
#sys.path.append('/usr/lib/python3/dist-packages')
#sys.path.append('/volume1/@appstore/python3/lib/python3.5/site-packages')
#sys.path.append('/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages')
#sys.path.append('C:\\Program Files (x86)\\Python37-32\\Lib\\site-packages')

I copied all modules downloaded using pip3 install -r requirements.txt to '/usr/lib/python3/dist-packages':

$ ls -la /usr/lib/python3/dist-packages | grep fritz
-rwxr-xr-x 1 root root 231 Apr 5 21:37 fritzcall
-rwxr-xr-x 1 root root 237 Apr 5 21:37 fritzconnection
-rwxr-xr-x 1 root root 235 Apr 5 21:37 fritzhomeauto
-rwxr-xr-x 1 root root 232 Apr 5 21:37 fritzhosts
-rwxr-xr-x 1 root root 236 Apr 5 21:37 fritzphonebook
-rwxr-xr-x 1 root root 233 Apr 5 21:37 fritzstatus
-rwxr-xr-x 1 root root 231 Apr 5 21:37 fritzwlan

My other python based plugins are working properly.

Any hint what am I doing wrong?

**Comment by belzetrigger** [comment]
Looks like python lib is not found. I install libs usually as sudo straight on my raspberry. And all related libs are installed as well.

Please try
- check if lib is correctly installed:  pip3 show fritzconnection
- you should see output with some information about fritzconnection
```xxx:~ $ pip3 show fritzconnection 
Name: fritzconnection
Version: 1.2.1
Summary: Communicate with the AVM FritzBox
Home-page: https://github.com/kbr/fritzconnection
Author: Klaus Bremer
Author-email: bremer@bremer-media.de
License: MIT
Location: /usr/local/lib/python3.7/dist-packages
Requires: requests
Required-by:
```
- make sure it has version 1.2.1, with older versions and lxml dependency I had trouble as well 
- check if fritzconnection works by just running:
```xxx:~ $ fritzconnection
FritzConnection v1.2.1
FRITZ!Box 7590 at http://169.254.1.1
FRITZ!OS: 7.12
```
for my raspbian environment  I did:

- installed python lib with sudo: `sudo pip3 install -r requirements.txt` 
- test if fritzconnections works
- comment out all -> `# sys.path` in plugin.py and fritzHelper.py
- worked also with them, but the where more for windows and synology
- restarted domoticz service `sudo systemctl restart domoticz.service`
- add device

**Comment by santricity** [comment]
Hi, many thanks for this! It is now working properly! What I did, I ran  'pip3 install fritzconnection' as a root, not as a pi user with sudo.
